version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: gem install awesome_bot danger
      - run: awesome_bot --allow-redirect --allow-dupe -w awesome_bot --allow-redirect --allow-dupe -w https://github.com/Shift3,regexr,127.0.0.1 `find . -name "*.md"`
      - run: bundle exec danger --verbose