version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: gem install awesome_bot
      - run: awesome_bot --allow-redirect --allow-dupe -w https://github.com/Shift3/ifg `find . -name "*.md"`